{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wear-compose-material3/1.7.0-beta02-cmp08/wear-compose-material3-1.7.0-beta02-cmp08.module",
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-material3",
    "version": "1.7.0-beta02-cmp08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-beta02-cmp08"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-beta02-cmp08"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp08.klib",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp08.klib",
          "size": 2064365,
          "sha512": "63af8f3fb9b83b9aa28e13e3f5149f179f7a54661ca709983264b177dbfd430b1ee50001e9ac80f946388cf7ca44be540ad7b96b293cc13c515cbba6cf181606",
          "sha256": "0b342fcfa74b9a94e45c9af62ed3f0935fc4585c0705f7aeb760a5f41903e0e7",
          "sha1": "f24d913ac27cf4dcb9b953fe48b5ca21474d3351",
          "md5": "462abf80271e3f59ea82e097be5d7246"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-beta02-cmp08"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-beta02-cmp08"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp08.klib",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp08.klib",
          "size": 2064365,
          "sha512": "63af8f3fb9b83b9aa28e13e3f5149f179f7a54661ca709983264b177dbfd430b1ee50001e9ac80f946388cf7ca44be540ad7b96b293cc13c515cbba6cf181606",
          "sha256": "0b342fcfa74b9a94e45c9af62ed3f0935fc4585c0705f7aeb760a5f41903e0e7",
          "sha1": "f24d913ac27cf4dcb9b953fe48b5ca21474d3351",
          "md5": "462abf80271e3f59ea82e097be5d7246"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp08-sources.jar",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp08-sources.jar",
          "size": 486140,
          "sha512": "a04288ae86e15f48ea593e59afce401a803f98ce149e97ed18ef78022d91a33641e219a5f172a8c613cfcdd1c3c338932d09274272e69313dbde68f1f0009aa7",
          "sha256": "70992e3430e969cba9f1827e24e0e9af1a6d0f696edc97d9990a65245219fc30",
          "sha1": "c97fa50e3abef35c0467cfcc9ee19f47361b6c77",
          "md5": "32dcd4ddc2fce7b686be514dd6d0feba"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-beta02-cmp08"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-beta02-cmp08"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-1.7.0-beta02-cmp08.kotlin_resources.zip",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp08-kotlin_resources.kotlin_resources.zip",
          "size": 4531,
          "sha512": "805aac3c66fd38dc276403ec2875326cbcf2616e32e2070f97ca451538a639b6bc17ee83d3eaf909c309435525b69d7e3e2ed9069e970ed2e1c402f58518a018",
          "sha256": "10e305bf63fc2c57b4b42a5a763b13a72eac4c331e1b22957072dcf9e7d7de29",
          "sha1": "2c2d6c8130a4e9c3cd1ae99ce5eac43b22908092",
          "md5": "a52d8f4aa36465cc2ff461f79799e9c7"
        }
      ]
    }
  ]
}
