{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wear-compose-foundation/1.7.0-beta02-cmp01/wear-compose-foundation-1.7.0-beta02-cmp01.module",
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-foundation",
    "version": "1.7.0-beta02-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-foundation-jvm-1.7.0-beta02-cmp01.jar",
          "url": "wear-compose-foundation-jvm-1.7.0-beta02-cmp01.jar",
          "size": 936150,
          "sha512": "6d851bc1dc2f13749976d81d4cddc4ed1b34aa5bc1f52fc3e330dfa8230458a195b886d772ceae45c053735936bb60096f06a7dd4f773971316cf8f5057c85bb",
          "sha256": "6609d8534633814b1155903bc968d42e5a610fec577f7d3b7049bf03cba15ee7",
          "sha1": "3a37af852bd7a2868afd3f431a5884ad79219e7c",
          "md5": "fac00cad729f9fde5ab315cb41ce4e51"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-foundation-jvm-1.7.0-beta02-cmp01.jar",
          "url": "wear-compose-foundation-jvm-1.7.0-beta02-cmp01.jar",
          "size": 936150,
          "sha512": "6d851bc1dc2f13749976d81d4cddc4ed1b34aa5bc1f52fc3e330dfa8230458a195b886d772ceae45c053735936bb60096f06a7dd4f773971316cf8f5057c85bb",
          "sha256": "6609d8534633814b1155903bc968d42e5a610fec577f7d3b7049bf03cba15ee7",
          "sha1": "3a37af852bd7a2868afd3f431a5884ad79219e7c",
          "md5": "fac00cad729f9fde5ab315cb41ce4e51"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "wear-compose-foundation-jvm-1.7.0-beta02-cmp01-sources.jar",
          "url": "wear-compose-foundation-jvm-1.7.0-beta02-cmp01-sources.jar",
          "size": 223492,
          "sha512": "83c4ae9da2bb20b4c9969834e6a502b16381e2eecaaf0a35672f42e547c5583058c524f0aa9a347149f29178fa6bab1ed5e555a10dfeaf5f189335ad3fac5250",
          "sha256": "ae80f6271c951e0547bea8d8e85ded702f68732e1a470583b15999cc369c1ce4",
          "sha1": "6486eb28053f01c7d64e30e31d76b1a5acb5e251",
          "md5": "69c31c380b0307e9b7273097f5486f6c"
        }
      ]
    }
  ]
}
