{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-foundation",
    "version": "1.7.0-beta02-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-foundation-metadata-1.7.0-beta02-cmp01.jar",
          "url": "wear-compose-foundation-1.7.0-beta02-cmp01.jar",
          "size": 85416,
          "sha512": "7110914d5f3852eb702f41dc7001b4903fa15c645e603b20c82cf475bc72cfe07a57b5bd74453f71f9e0e9645f2b1d7918fc3563f87c896fae16d5ad7d616a3e",
          "sha256": "63da8b80212faa6f147a2eed63f6de318091a47ef9afcbf467f58f5272add14f",
          "sha1": "411ed933876e4d714d2c6d164f90250bee5bb360",
          "md5": "e643476bfdbf30a284eb33df4c8f1e29"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "wear-compose-foundation-kotlin-1.7.0-beta02-cmp01-sources.jar",
          "url": "wear-compose-foundation-1.7.0-beta02-cmp01-sources.jar",
          "size": 223492,
          "sha512": "83c4ae9da2bb20b4c9969834e6a502b16381e2eecaaf0a35672f42e547c5583058c524f0aa9a347149f29178fa6bab1ed5e555a10dfeaf5f189335ad3fac5250",
          "sha256": "ae80f6271c951e0547bea8d8e85ded702f68732e1a470583b15999cc369c1ce4",
          "sha1": "6486eb28053f01c7d64e30e31d76b1a5acb5e251",
          "md5": "69c31c380b0307e9b7273097f5486f6c"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-jvm/1.7.0-beta02-cmp01/wear-compose-foundation-jvm-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-jvm",
        "version": "1.7.0-beta02-cmp01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-jvm/1.7.0-beta02-cmp01/wear-compose-foundation-jvm-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-jvm",
        "version": "1.7.0-beta02-cmp01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-jvm/1.7.0-beta02-cmp01/wear-compose-foundation-jvm-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-jvm",
        "version": "1.7.0-beta02-cmp01"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-wasm-js/1.7.0-beta02-cmp01/wear-compose-foundation-wasm-js-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-wasm-js",
        "version": "1.7.0-beta02-cmp01"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-wasm-js/1.7.0-beta02-cmp01/wear-compose-foundation-wasm-js-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-wasm-js",
        "version": "1.7.0-beta02-cmp01"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-wasm-js/1.7.0-beta02-cmp01/wear-compose-foundation-wasm-js-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-wasm-js",
        "version": "1.7.0-beta02-cmp01"
      }
    }
  ]
}
