#!/usr/bin/env bash
# Shared agent-attribution detector.
#
# ONE implementation, FOUR callers — the local `commit-msg` hook, the local
# `pre-push` hook, the PR-layer CI check, and the post-merge drift check on the
# default branch. They MUST agree, so the matching lives here rather than being
# copy-pasted into each caller: a gate that disagrees with itself is worse than
# no gate.
#
# What is rejected (deliberately narrow) — only the things that make git history
# claim an AI agent authored the work:
#   1. a commit whose AUTHOR or COMMITTER identity is an agent — an agent email
#      domain (@anthropic.com, @openai.com, …) or an agent *name* set literally
#      as the identity ("Claude", "Codex", …), and
#   2. a `Co-authored-by:` trailer, at trailer position (start of line), naming
#      an agent or using an agent email.
#
# What is FINE and intentionally not matched: links to an agent session
# (claude.ai/code), the "🤖 Generated with …" and "_Generated by [Claude Code]_"
# footers, ordinary prose, and PR comments. Those don't claim authorship.
#
# GitHub App bot accounts are exempt from the IDENTITY check (1) but not from
# the trailer check (2). The name match is anchored to the whole field, so
# "claude[bot]" and a human named "Claude Martin" both pass (1); a
# `Co-authored-by: claude[bot] …` trailer still fails (2), because a trailer is
# an authorship claim wherever it came from.
#
# Usage:
#   agent-attribution-scan.sh [--range <rev>]... [--text-file <file>]...
#                             [--ident <role> <ident>]...
#                             [--rev-args <rev>...]
#
#   --range      a `git log` revision argument — a range (<base>..<head>) or a
#                single commit (meaning "everything reachable from it").
#   --text-file  extra text scanned for trailers — the PR title + body (which
#                the squash commit message is built from), or a commit message
#                file at commit-msg time.
#   --ident      a literal "<role>" "<Name> <<email>>" pair to check, for the
#                commit-msg hook where the commit does not exist yet. Take the
#                value from `git var GIT_AUTHOR_IDENT`.
#   --rev-args   everything after this flag is passed to `git log` verbatim,
#                for callers that need `<sha> --not --remotes=origin` and the
#                like. Must come last.
#
# Exit codes:
#   0  nothing found
#   1  agent attribution found (records printed to stderr)
#   2  could not scan — bad arguments, or a revision that does not resolve
#
# FAIL CLOSED. `git log` on an unresolvable revision exits nonzero and writes
# nothing; with only `set -uo pipefail` that sails through and reports "no agent
# attribution found" with exit 0 — a gate silently passing because it scanned an
# empty set. Every `git log` status is therefore checked explicitly, and an
# unresolvable revision is exit 2, never exit 0.
#
# Keep AGENT_NAME / AGENT_EMAIL in sync across the sibling repos that vendor
# this script (compose-ai-tools, meshcore-mobile, homeassistant-remotecompose,
# compose-samples).
set -uo pipefail

# IDENTITY vocabulary — matched against a commit's author/committer fields. The
# name is matched ANCHORED (see below), so it must stay a list of bare agent
# names: a token that also occurs in human names would reject real people.
AGENT_NAME='(claude|codex|chatgpt|copilot|gemini|cursor|devin|aider|jules)'
AGENT_EMAIL='@(anthropic[.]com|openai[.]com|cursor[.](sh|com)|devin[.]ai|sourcegraph[.]com|continue[.]dev|factory[.]ai)'

# TRAILER vocabulary — matched anywhere after `Co-authored-by:`. Deliberately
# WIDER than the identity vocabulary, and it must stay that way: a trailer is
# free-form text an agent writes about itself, so it carries product names and
# vendor domains that never appear as a git identity. This is the list the
# pre-existing workflow gates used; do not trim it without replacing the
# coverage, or attribution the old gate rejected starts sailing through all
# four layers at once.
AGENT_TRAILER='(claude|anthropic[.]com|copilot|openai[.]com|chatgpt|codex|gemini|cursor[.](com|sh)|devin|aider|jules|sourcegraph[.]com|cody-ai|bard|sweep-ai|tabnine|codeium|continue[.]dev|replit-ai|amazonq|amazon-q|codewhisperer|qodo|bito-ai|cognition-ai|factory[.]ai|noreply@.*-ai|.*-bot@)'

revs=()
text_files=()
ident_roles=()
ident_values=()

usage() {
  printf 'agent-attribution-scan: %s\n' "$1" >&2
  printf 'usage: agent-attribution-scan.sh [--range <rev>]... [--text-file <f>]... [--ident <role> <ident>]... [--rev-args <rev>...]\n' >&2
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --range)
      [ $# -ge 2 ] || usage "--range needs a value"
      revs+=("$2"); shift 2 ;;
    --text-file)
      [ $# -ge 2 ] || usage "--text-file needs a value"
      text_files+=("$2"); shift 2 ;;
    --ident)
      [ $# -ge 3 ] || usage "--ident needs a role and an identity"
      ident_roles+=("$2"); ident_values+=("$3"); shift 3 ;;
    --rev-args)
      shift
      [ $# -ge 1 ] || usage "--rev-args needs at least one revision"
      revs+=("$@"); break ;;
    *)
      usage "unknown argument: $1" ;;
  esac
done

if [ "${#revs[@]}" -eq 0 ] && [ "${#text_files[@]}" -eq 0 ] && [ "${#ident_values[@]}" -eq 0 ]; then
  usage "nothing to scan — pass at least one of --range / --text-file / --ident"
fi

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

problems=""

# ---------------------------------------------------------------------------
# 1. Literal identities supplied by the caller (`--ident`).
#
#    The commit-msg hook runs BEFORE the commit object exists, so there is
#    nothing for `git log` to read. It passes `git var GIT_AUTHOR_IDENT` /
#    GIT_COMMITTER_IDENT here instead, which is the same pair of fields the
#    range scan below reads off finished commits.
# ---------------------------------------------------------------------------
i=0
while [ "$i" -lt "${#ident_values[@]}" ]; do
  role="${ident_roles[$i]}"
  ident="${ident_values[$i]}"
  i=$((i + 1))
  # "A U Thor <author@example.com> 1712345678 +0000" -> name / email
  name="$(printf '%s' "$ident" | sed -n 's/ <[^>]*>.*//p')"
  email="$(printf '%s' "$ident" | sed -n 's/.*<\([^>]*\)>.*/\1/p')"
  if printf '%s' "$email" | grep -Eqi "$AGENT_EMAIL"; then
    problems="${problems}${role} email '${email}' is an AI agent.
"
  elif printf '%s' "$name" | grep -Eqi "^${AGENT_NAME}$"; then
    problems="${problems}${role} name '${name}' is an AI agent.
"
  fi
done

# ---------------------------------------------------------------------------
# 2. Author / committer identity of every commit in the given revisions.
#
#    This is also what produces a `Co-authored-by:` trailer on the default
#    branch: GitHub's squash credits every distinct commit author of the branch
#    as a co-author, so an agent identity here lands a trailer even when the PR
#    title and body are spotless.
#
#    One record per identity: <sha>\t<role>\t<name>\t<email>.
# ---------------------------------------------------------------------------
: > "$workdir/idents.txt"
: > "$workdir/messages.txt"
if [ "${#revs[@]}" -gt 0 ]; then
  if ! git log \
    --format='%H%x09author%x09%an%x09%ae%x0a%H%x09committer%x09%cn%x09%ce' \
    "${revs[@]}" > "$workdir/idents.txt" 2> "$workdir/git.err"; then
    printf 'agent-attribution-scan: cannot resolve revision arguments (%s) — refusing to report clean.\n' \
      "${revs[*]}" >&2
    sed 's/^/  git: /' "$workdir/git.err" >&2
    exit 2
  fi
  if ! git log --format='%B' "${revs[@]}" > "$workdir/messages.txt" 2> "$workdir/git.err"; then
    printf 'agent-attribution-scan: cannot read commit messages for (%s) — refusing to report clean.\n' \
      "${revs[*]}" >&2
    sed 's/^/  git: /' "$workdir/git.err" >&2
    exit 2
  fi
fi

# tolower() rather than IGNORECASE so this holds on mawk (the default awk on
# ubuntu-latest) as well as gawk. The email match is a substring (any
# …@anthropic.com / …@openai.com address), but the NAME match is anchored to the
# whole identity ("^…$") so it catches an identity set literally to
# "Claude"/"Codex"/… without snagging a human whose name merely contains the
# token ("Claude Martin", "Alice Copilotson") — and it naturally exempts GitHub
# App bots, whose name is "claude[bot]", not "claude".
ident_hits="$(awk -F'\t' -v nre="$AGENT_NAME" -v ere="$AGENT_EMAIL" '
  BEGIN { nre = tolower(nre); ere = tolower(ere) }
  tolower($4) ~ ere            { print; next }
  tolower($3) ~ ("^" nre "$")  { print }
' "$workdir/idents.txt" || true)"
if [ -n "$ident_hits" ]; then
  problems="${problems}Commit author/committer identity is an agent:
${ident_hits}
"
fi

# ---------------------------------------------------------------------------
# 3. Co-authored-by trailers (start-of-line only) in the commit messages and in
#    any supplied text — flagged when the name or email is an agent. Trailer
#    position only, so prose that merely *mentions* a trailer (like the comment
#    at the top of this file) does not trip the gate.
# ---------------------------------------------------------------------------
cat "$workdir/messages.txt" > "$workdir/all_text.txt"
for f in ${text_files[@]+"${text_files[@]}"}; do
  if ! cat "$f" >> "$workdir/all_text.txt"; then
    printf 'agent-attribution-scan: cannot read --text-file %s — refusing to report clean.\n' \
      "$f" >&2
    exit 2
  fi
done

coauthor_hits="$(grep -iE '^[[:space:]]*Co-authored-by:' "$workdir/all_text.txt" \
                 | grep -Ei "Co-authored-by:.*${AGENT_TRAILER}" \
                 || true)"
if [ -n "$coauthor_hits" ]; then
  problems="${problems}Agent Co-authored-by trailer(s):
${coauthor_hits}
"
fi

if [ -n "$problems" ]; then
  printf '%s\n' "$problems" >&2
  exit 1
fi

echo "No agent co-author trailers or agent commit identities found."
