{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.wearcmp",
    "module": "port-runtime",
    "version": "1.7.0-beta02-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-metadata-1.7.0-beta02-cmp01.jar",
          "url": "port-runtime-1.7.0-beta02-cmp01.jar",
          "size": 8453,
          "sha512": "fc5694b17002dd20f0db67ceaa2fc4eeac348b53f916c5deb552cfcc4a637af30ffabe0dad65f7d64f2a22f77a1f7027b51d48a94c3c89ac46d86466ce886c9f",
          "sha256": "4fdba6807db8809c29569a88e39888e7df914c4523964b3daf867fdfa0c9d80e",
          "sha1": "9eaeebd1fe9a317e71986b83d7e5a01f8a1cff22",
          "md5": "c05113db847248691d531ff466132b33"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "port-runtime-kotlin-1.7.0-beta02-cmp01-sources.jar",
          "url": "port-runtime-1.7.0-beta02-cmp01-sources.jar",
          "size": 16667,
          "sha512": "721c0b66a1f62ffec411ec489ddb95e28db0245b849a9974126d91c7925db131d43731ad0cd007c19de8e4f46fb37116ca5325fbfd3d636d3fc7da5c6812f78c",
          "sha256": "0879590529c170b7ad45cfe49c0dc50efb36321b310879d0ecd1fe037794de2f",
          "sha1": "ad9442a782dfef25cb6574e3a0eb8f201829ecb2",
          "md5": "0c6e4365ff158a4f6dadc545fc29167a"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../port-runtime-jvm/1.7.0-beta02-cmp01/port-runtime-jvm-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "port-runtime-jvm",
        "version": "1.7.0-beta02-cmp01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../port-runtime-jvm/1.7.0-beta02-cmp01/port-runtime-jvm-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "port-runtime-jvm",
        "version": "1.7.0-beta02-cmp01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../port-runtime-jvm/1.7.0-beta02-cmp01/port-runtime-jvm-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "port-runtime-jvm",
        "version": "1.7.0-beta02-cmp01"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../port-runtime-wasm-js/1.7.0-beta02-cmp01/port-runtime-wasm-js-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "port-runtime-wasm-js",
        "version": "1.7.0-beta02-cmp01"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../port-runtime-wasm-js/1.7.0-beta02-cmp01/port-runtime-wasm-js-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "port-runtime-wasm-js",
        "version": "1.7.0-beta02-cmp01"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../port-runtime-wasm-js/1.7.0-beta02-cmp01/port-runtime-wasm-js-1.7.0-beta02-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "port-runtime-wasm-js",
        "version": "1.7.0-beta02-cmp01"
      }
    }
  ]
}
