/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.wear.compose.material3.internal

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.text.intl.Locale
import kotlin.jvm.JvmInline

/*
 * Replaces the generated `internal/Strings.kt`, which is excluded in `transform-rules.json`.
 *
 * Upstream's version is 23 `Strings(R.string.…)` constants resolved through `stringResource`, and
 * `R` is generated by aapt from resources an off-Android build has no equivalent of. What survives
 * unchanged is the SHAPE: an internal value class per string, and `getString`/`getPlurals` to read
 * one in composition — so every call site in the 30-odd files that use them is untouched.
 *
 * The text itself is not restated here. It comes from `GeneratedResources.kt`, generated from the
 * AAR's own `res/values/values.xml` by `tools/transform.py`, so an upstream wording change lands
 * with the next sync. Only the mapping from Kotlin name to resource name lives here, because that
 * mapping is not derivable — `wear_m3c_slider_decrease_content_description` is
 * `SliderDecreaseIconContentDescription`, and no rule produces that.
 *
 * Localised: every locale the AAR ships is generated, and the text is chosen against the
 * composition's own `Locale.current`. Plural forms are chosen by the locale's own CLDR category —
 * see `PluralRules.kt`. What is NOT reproduced is Android's full resource resolution: there are no
 * script or region fallback chains beyond the two steps in [localeCandidates].
 */

@Composable
@ReadOnlyComposable
internal fun getString(string: Strings): String = string.textIn(Locale.current)

@Composable
@ReadOnlyComposable
internal fun getString(string: Strings, vararg formatArgs: Any): String =
    string.textIn(Locale.current).formatResource(formatArgs)

@Composable
@ReadOnlyComposable
internal fun getPlurals(plurals: Plurals, quantity: Int): String =
    plurals.textIn(Locale.current, quantity)

@Composable
@ReadOnlyComposable
internal fun getPlurals(plurals: Plurals, quantity: Int, vararg formatArgs: Any): String =
    plurals.textIn(Locale.current, quantity).formatResource(formatArgs)

/**
 * The tags to try, most specific first: `pt-BR` before `pt`, as Android resolves `values-pt-rBR`
 * before `values-pt`. A tag matching neither falls through to the default locale.
 */
private fun localeCandidates(locale: Locale): List<String> {
    val language = locale.language
    val region = locale.region
    return if (region.isEmpty()) listOf(language) else listOf("$language-$region", language)
}

@JvmInline
@Immutable
internal value class Strings(val resourceName: String) {
    fun textIn(locale: Locale): String {
        for (tag in localeCandidates(locale)) {
            GeneratedLocalizedStrings[tag]?.get(resourceName)?.let {
                return it
            }
        }
        // Falling back to the default locale, and then to the resource name rather than throwing:
        // a missing string should show up as an odd content description in an accessibility tree,
        // not as a crash in a watch face.
        return GeneratedStrings[resourceName] ?: resourceName
    }

    companion object {
        inline val TimePickerHour
            get() = Strings("wear_m3c_time_picker_hour")

        inline val TimePickerMinute
            get() = Strings("wear_m3c_time_picker_minute")

        inline val TimePickerSecond
            get() = Strings("wear_m3c_time_picker_second")

        inline val TimePickerPeriod
            get() = Strings("wear_m3c_time_picker_period")

        inline val TimePickerHeading
            get() = Strings("wear_m3c_time_picker_heading")

        inline val DatePickerYear
            get() = Strings("wear_m3c_date_picker_year")

        inline val DatePickerMonth
            get() = Strings("wear_m3c_date_picker_month")

        inline val DatePickerDay
            get() = Strings("wear_m3c_date_picker_day")

        inline val DatePickerHeading
            get() = Strings("wear_m3c_date_picker_heading")

        inline val PickerClickToAdjustHint
            get() = Strings("wear_m3c_picker_click_to_adjust_hint")

        inline val PickerClickToSelectHint
            get() = Strings("wear_m3c_picker_click_to_select_hint")

        inline val PickerConfirmButtonContentDescription
            get() = Strings("wear_m3c_picker_confirm_button_content_description")

        inline val PickerNextButtonContentDescription
            get() = Strings("wear_m3c_picker_next_button_content_description")

        inline val SliderDecreaseIconContentDescription
            get() = Strings("wear_m3c_slider_decrease_content_description")

        inline val SliderIncreaseIconContentDescription
            get() = Strings("wear_m3c_slider_increase_content_description")

        inline val AlertDialogContentDescriptionConfirmButton
            get() = Strings("wear_m3c_alert_dialog_content_description_confirm_button")

        inline val AlertDialogContentDescriptionDismissButton
            get() = Strings("wear_m3c_alert_dialog_content_description_dismiss_button")

        inline val OpenOnPhoneContentDescriptionIcon
            get() = Strings("wear_m3c_open_on_phone_icon_content_description")

        inline val OnStateDescription
            get() = Strings("wear_m3c_capital_on_state_description")

        inline val OffStateDescription
            get() = Strings("wear_m3c_capital_off_state_description")

        inline val CheckedStateDescription
            get() = Strings("wear_m3c_checked_state_description")

        inline val NotCheckedStateDescription
            get() = Strings("wear_m3c_not_checked_state_description")

        inline val DatePickerContentDescription
            get() = Strings("wear_m3c_date_picker_content_description")
    }
}

@JvmInline
@Immutable
internal value class Plurals(val resourceName: String) {
    /**
     * The grammatical form [quantity] takes in this locale, by CLDR's rules — see [pluralCategory].
     *
     * The keyword is chosen per CANDIDATE TAG rather than once up front, because the tag decides
     * the rule as well as the text: `pt-PT` takes `one` for 1 alone where `pt` takes it for 0 and 1,
     * so choosing against the locale and then reading from a fallback tag could pick a form by the
     * wrong language's rule.
     *
     * `other` remains the fallback when a translation ships no form under the chosen keyword. That
     * is not a shortcut: CLDR only requires the forms a language actually distinguishes, and
     * `other` is the one every locale defines.
     */
    fun textIn(locale: Locale, quantity: Int): String {
        for (tag in localeCandidates(locale)) {
            val forms = GeneratedLocalizedPlurals[tag]?.get(resourceName) ?: continue
            val keyword = pluralCategory(tag, quantity).keyword
            (forms[keyword] ?: forms["other"])?.let {
                return it
            }
        }
        // The default resources, which are the English ones — so English's rule chooses among them.
        val forms = GeneratedPlurals[resourceName] ?: return resourceName
        val keyword = pluralCategory("en", quantity).keyword
        return forms[keyword] ?: forms["other"] ?: resourceName
    }

    companion object {
        inline val TimePickerHoursContentDescription
            get() = Plurals("wear_m3c_time_picker_hours_content_description")

        inline val TimePickerMinutesContentDescription
            get() = Plurals("wear_m3c_time_picker_minutes_content_description")

        inline val TimePickerSecondsContentDescription
            get() = Plurals("wear_m3c_time_picker_seconds_content_description")
    }
}

/**
 * The subset of `String.format` the Wear resources actually use, which is more than it looks:
 * `%s` and `%d`, and the POSITIONAL forms `%1$s` and `%2$d` that the translations rely on — the
 * date picker's content description is `"%1$s, %2$d"`, and several translations reorder the two.
 * `%%` is a literal percent. Anything else is passed through unchanged rather than guessed at.
 *
 * Kotlin common has no `String.format`, and pulling one in for three call sites would be a bigger
 * dependency than the substitution it performs.
 */
private fun String.formatResource(args: Array<out Any>): String {
    val out = StringBuilder(length)
    var index = 0
    var next = 0
    while (index < length) {
        val char = this[index]
        if (char != '%' || index == lastIndex) {
            out.append(char)
            index++
            continue
        }

        // `%<n>$` selects an argument explicitly; without it they are taken in order.
        var cursor = index + 1
        var explicit = -1
        var digits = cursor
        while (digits < length && this[digits].isDigit()) digits++
        if (digits > cursor && digits < length && this[digits] == '$') {
            explicit = substring(cursor, digits).toInt() - 1
            cursor = digits + 1
        }
        if (cursor >= length) {
            out.append(char)
            index++
            continue
        }

        when (val conversion = this[cursor]) {
            '%' -> out.append('%')
            'd',
            's' -> {
                val argument = if (explicit >= 0) explicit else next++
                out.append(args.getOrNull(argument)?.toString() ?: "")
            }
            else -> out.append(substring(index, cursor + 1))
        }
        index = cursor + 1
    }
    return out.toString()
}

/**
 * Substitute [args] into a resource template. `formatResource` is private to this file; this is the
 * way in for the one ported component that formats a template itself (`DatePicker`'s content
 * description, which upstream builds with `String.format(locale, …)`) and for the tests.
 */
internal fun formatTemplate(text: String, args: Array<out Any>): String = text.formatResource(args)
