/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.wear.compose.material3.internal

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import kotlin.jvm.JvmInline

/*
 * Replaces the generated `internal/Strings.kt`, which is excluded in `transform-rules.json`.
 *
 * Upstream's version is 23 `Strings(R.string.…)` constants resolved through `stringResource`, and
 * `R` is generated by aapt from resources an off-Android build has no equivalent of. What survives
 * unchanged is the SHAPE: an internal value class per string, and `getString`/`getPlurals` to read
 * one in composition — so every call site in the 30-odd files that use them is untouched.
 *
 * The text itself is not restated here. It comes from `GeneratedResources.kt`, generated from the
 * AAR's own `res/values/values.xml` by `tools/transform.py`, so an upstream wording change lands
 * with the next sync. Only the mapping from Kotlin name to resource name lives here, because that
 * mapping is not derivable — `wear_m3c_slider_decrease_content_description` is
 * `SliderDecreaseIconContentDescription`, and no rule produces that.
 *
 * Localisation is the known gap: the AAR ships 80 more locales and the port takes only the
 * default. See docs/PIPELINE.md -> Localisation.
 */

@Composable
@ReadOnlyComposable
internal fun getString(string: Strings): String = string.text

@Composable
@ReadOnlyComposable
internal fun getString(string: Strings, vararg formatArgs: Any): String =
    string.text.formatResource(formatArgs)

@Composable
@ReadOnlyComposable
internal fun getPlurals(plurals: Plurals, quantity: Int): String = plurals.text(quantity)

@Composable
@ReadOnlyComposable
internal fun getPlurals(plurals: Plurals, quantity: Int, vararg formatArgs: Any): String =
    plurals.text(quantity).formatResource(formatArgs)

@JvmInline
@Immutable
internal value class Strings(val resourceName: String) {
    val text: String
        // Falling back to the resource name rather than throwing: a missing string should show up
        // as an odd content description in an accessibility tree, not as a crash in a watch face.
        get() = GeneratedStrings[resourceName] ?: resourceName

    companion object {
        inline val TimePickerHour
            get() = Strings("wear_m3c_time_picker_hour")

        inline val TimePickerMinute
            get() = Strings("wear_m3c_time_picker_minute")

        inline val TimePickerSecond
            get() = Strings("wear_m3c_time_picker_second")

        inline val TimePickerPeriod
            get() = Strings("wear_m3c_time_picker_period")

        inline val TimePickerHeading
            get() = Strings("wear_m3c_time_picker_heading")

        inline val DatePickerYear
            get() = Strings("wear_m3c_date_picker_year")

        inline val DatePickerMonth
            get() = Strings("wear_m3c_date_picker_month")

        inline val DatePickerDay
            get() = Strings("wear_m3c_date_picker_day")

        inline val DatePickerHeading
            get() = Strings("wear_m3c_date_picker_heading")

        inline val PickerClickToAdjustHint
            get() = Strings("wear_m3c_picker_click_to_adjust_hint")

        inline val PickerClickToSelectHint
            get() = Strings("wear_m3c_picker_click_to_select_hint")

        inline val PickerConfirmButtonContentDescription
            get() = Strings("wear_m3c_picker_confirm_button_content_description")

        inline val PickerNextButtonContentDescription
            get() = Strings("wear_m3c_picker_next_button_content_description")

        inline val SliderDecreaseIconContentDescription
            get() = Strings("wear_m3c_slider_decrease_content_description")

        inline val SliderIncreaseIconContentDescription
            get() = Strings("wear_m3c_slider_increase_content_description")

        inline val AlertDialogContentDescriptionConfirmButton
            get() = Strings("wear_m3c_alert_dialog_content_description_confirm_button")

        inline val AlertDialogContentDescriptionDismissButton
            get() = Strings("wear_m3c_alert_dialog_content_description_dismiss_button")

        inline val OpenOnPhoneContentDescriptionIcon
            get() = Strings("wear_m3c_open_on_phone_icon_content_description")

        inline val OnStateDescription
            get() = Strings("wear_m3c_capital_on_state_description")

        inline val OffStateDescription
            get() = Strings("wear_m3c_capital_off_state_description")

        inline val CheckedStateDescription
            get() = Strings("wear_m3c_checked_state_description")

        inline val NotCheckedStateDescription
            get() = Strings("wear_m3c_not_checked_state_description")

        inline val DatePickerContentDescription
            get() = Strings("wear_m3c_date_picker_content_description")
    }
}

@JvmInline
@Immutable
internal value class Plurals(val resourceName: String) {
    /**
     * Android picks the plural form with ICU rules per locale. Only the default locale is present
     * (see the file header), and English distinguishes exactly one from everything else, so that
     * is the rule applied — `other` is the fallback for any quantity a resource does not name.
     */
    fun text(quantity: Int): String {
        val forms = GeneratedPlurals[resourceName] ?: return resourceName
        val keyword = if (quantity == 1) "one" else "other"
        return forms[keyword] ?: forms["other"] ?: resourceName
    }

    companion object {
        inline val TimePickerHoursContentDescription
            get() = Plurals("wear_m3c_time_picker_hours_content_description")

        inline val TimePickerMinutesContentDescription
            get() = Plurals("wear_m3c_time_picker_minutes_content_description")

        inline val TimePickerSecondsContentDescription
            get() = Plurals("wear_m3c_time_picker_seconds_content_description")
    }
}

/**
 * The subset of `String.format` the Wear resources actually use: `%d` and `%s`, positionally, plus
 * `%%`. Kotlin common has no `String.format`, and pulling one in for three call sites would be a
 * bigger dependency than the substitution it performs.
 */
private fun String.formatResource(args: Array<out Any>): String {
    val out = StringBuilder(length)
    var index = 0
    var next = 0
    while (index < length) {
        val char = this[index]
        if (char != '%' || index == lastIndex) {
            out.append(char)
            index++
            continue
        }
        when (val specifier = this[index + 1]) {
            '%' -> out.append('%')
            'd',
            's' -> out.append(args.getOrNull(next++)?.toString() ?: "")
            else -> out.append('%').append(specifier)
        }
        index += 2
    }
    return out.toString()
}
