{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wear-compose-material3/1.7.0-beta02-cmp03/wear-compose-material3-1.7.0-beta02-cmp03.module",
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-material3",
    "version": "1.7.0-beta02-cmp03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-beta02-cmp03"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-beta02-cmp03"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp03.klib",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp03.klib",
          "size": 1993884,
          "sha512": "b1819564b63255251e1fc63554d94a9e9fdb8114128d7e1f27abc30689e03ea5c330117a94a10184b9be6e6d951ca207afac07789e22c213a55dca5d1ca941af",
          "sha256": "1d284aa8d3517460ffceb40b87b16478b0671b150582bf4836fe8bc14830eeaa",
          "sha1": "cab059dfa3b891229b17c9ea07aa1dcc7ed2b3ed",
          "md5": "8ae08b43e62883c4f1488f513bbb7b7d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-beta02-cmp03"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-beta02-cmp03"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp03.klib",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp03.klib",
          "size": 1993884,
          "sha512": "b1819564b63255251e1fc63554d94a9e9fdb8114128d7e1f27abc30689e03ea5c330117a94a10184b9be6e6d951ca207afac07789e22c213a55dca5d1ca941af",
          "sha256": "1d284aa8d3517460ffceb40b87b16478b0671b150582bf4836fe8bc14830eeaa",
          "sha1": "cab059dfa3b891229b17c9ea07aa1dcc7ed2b3ed",
          "md5": "8ae08b43e62883c4f1488f513bbb7b7d"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp03-sources.jar",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp03-sources.jar",
          "size": 466198,
          "sha512": "db5ef81321d88fa2f817c2c160178047a3639f58981acc4de9225efa487c50e344472c19747d36d630038341483a123169ed4dbf2f2ead2e7e6c6904e194c196",
          "sha256": "aef70417a312502d78f7907f475e5b5bc169be4eb5b0efa43f67fcd00ecc75b6",
          "sha1": "23e33a8ad8a152581ddbf7b6a518309c32984f48",
          "md5": "79862dbb3715fea46aa42722efdabf57"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-beta02-cmp03"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-beta02-cmp03"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-1.7.0-beta02-cmp03.kotlin_resources.zip",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp03-kotlin_resources.kotlin_resources.zip",
          "size": 4531,
          "sha512": "805aac3c66fd38dc276403ec2875326cbcf2616e32e2070f97ca451538a639b6bc17ee83d3eaf909c309435525b69d7e3e2ed9069e970ed2e1c402f58518a018",
          "sha256": "10e305bf63fc2c57b4b42a5a763b13a72eac4c331e1b22957072dcf9e7d7de29",
          "sha1": "2c2d6c8130a4e9c3cd1ae99ce5eac43b22908092",
          "md5": "a52d8f4aa36465cc2ff461f79799e9c7"
        }
      ]
    }
  ]
}
