{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-material3",
    "version": "1.7.0-beta02-cmp07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-beta02-cmp07"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-beta02-cmp07"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-metadata-1.7.0-beta02-cmp07.jar",
          "url": "wear-compose-material3-1.7.0-beta02-cmp07.jar",
          "size": 149428,
          "sha512": "e8df9afed6d61b1906a5368fbb73a390de9365a8a0c7f096e035ee171d4211e02e27ec4e605a74983ec4955243867f630f3c1b081514d67ce15f908437a6f2b5",
          "sha256": "65093925cbaa27a268b34b880696c17e6e88ce9f20f3bd016151f1d6b2b6d5a2",
          "sha1": "5548f5619254dcb36fda56e4ce2bb056f54a50d4",
          "md5": "625fee622db6c6a76808d0e2f094b529"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "wear-compose-material3-kotlin-1.7.0-beta02-cmp07-sources.jar",
          "url": "wear-compose-material3-1.7.0-beta02-cmp07-sources.jar",
          "size": 474107,
          "sha512": "301a95ff4169265610478b9f7e06a32592281b7e2339341fbd75c9b681f67b57248a6bee08c481220f8b1361b7dc96865f9ecdbd350c303f083a7726a58ada11",
          "sha256": "483b318d5c45990b289941ba3db609bc8d11f3c495cee8256aa397f8ec6de6df",
          "sha1": "8e06fce0626b850f9a96f1f9f6ee406cf7b68ba2",
          "md5": "736499076866c906362a339332036a08"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-material3-jvm/1.7.0-beta02-cmp07/wear-compose-material3-jvm-1.7.0-beta02-cmp07.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-jvm",
        "version": "1.7.0-beta02-cmp07"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-material3-jvm/1.7.0-beta02-cmp07/wear-compose-material3-jvm-1.7.0-beta02-cmp07.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-jvm",
        "version": "1.7.0-beta02-cmp07"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-material3-jvm/1.7.0-beta02-cmp07/wear-compose-material3-jvm-1.7.0-beta02-cmp07.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-jvm",
        "version": "1.7.0-beta02-cmp07"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-material3-wasm-js/1.7.0-beta02-cmp07/wear-compose-material3-wasm-js-1.7.0-beta02-cmp07.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-wasm-js",
        "version": "1.7.0-beta02-cmp07"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-material3-wasm-js/1.7.0-beta02-cmp07/wear-compose-material3-wasm-js-1.7.0-beta02-cmp07.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-wasm-js",
        "version": "1.7.0-beta02-cmp07"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-material3-wasm-js/1.7.0-beta02-cmp07/wear-compose-material3-wasm-js-1.7.0-beta02-cmp07.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-wasm-js",
        "version": "1.7.0-beta02-cmp07"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-material3-wasm-js/1.7.0-beta02-cmp07/wear-compose-material3-wasm-js-1.7.0-beta02-cmp07.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-wasm-js",
        "version": "1.7.0-beta02-cmp07"
      }
    }
  ]
}
