{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-foundation",
    "version": "1.7.0-beta02-cmp02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-foundation-metadata-1.7.0-beta02-cmp02.jar",
          "url": "wear-compose-foundation-1.7.0-beta02-cmp02.jar",
          "size": 87794,
          "sha512": "7b4df2a589eb0af95b1002e2f65049558a25d0c9bacc54b34bbc70d9e4ece05be7dc531a91f73169062ae9ec427f66e555e75d23caac29499abda8a90a59e899",
          "sha256": "657350617ac882bb3c494bd887ee775920d8a3638ea5c70c0c3be7fd52d7274d",
          "sha1": "5d7233e7adcf89b45367c011f3b5ee48354f410c",
          "md5": "c6ca018964ed1a3eedb1e05a4a651da9"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "wear-compose-foundation-kotlin-1.7.0-beta02-cmp02-sources.jar",
          "url": "wear-compose-foundation-1.7.0-beta02-cmp02-sources.jar",
          "size": 226262,
          "sha512": "df64233a376755fa5ffcb0fb93b5da3ec7804f9f850c126837903001afb9fb465dd7fda91640c4ee51cb3a1c8fe86778e96f4c986b968979f009adce34f0b1b8",
          "sha256": "b0925b2cd3f7cdc8717b93dca927a075d1da5376a82f78456a478b05f0770b4b",
          "sha1": "3356141e07cda430c1be8e5aed93e4cc6384615f",
          "md5": "aa6ce0d143f02ea756298443f96d1f9f"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-jvm/1.7.0-beta02-cmp02/wear-compose-foundation-jvm-1.7.0-beta02-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-jvm",
        "version": "1.7.0-beta02-cmp02"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-jvm/1.7.0-beta02-cmp02/wear-compose-foundation-jvm-1.7.0-beta02-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-jvm",
        "version": "1.7.0-beta02-cmp02"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-jvm/1.7.0-beta02-cmp02/wear-compose-foundation-jvm-1.7.0-beta02-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-jvm",
        "version": "1.7.0-beta02-cmp02"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-wasm-js/1.7.0-beta02-cmp02/wear-compose-foundation-wasm-js-1.7.0-beta02-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-wasm-js",
        "version": "1.7.0-beta02-cmp02"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-wasm-js/1.7.0-beta02-cmp02/wear-compose-foundation-wasm-js-1.7.0-beta02-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-wasm-js",
        "version": "1.7.0-beta02-cmp02"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-wasm-js/1.7.0-beta02-cmp02/wear-compose-foundation-wasm-js-1.7.0-beta02-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-wasm-js",
        "version": "1.7.0-beta02-cmp02"
      }
    }
  ]
}
