{
  "formatVersion": "1.1",
  "component": {
    "url": "../../port-runtime/1.7.0-beta02-cmp06/port-runtime-1.7.0-beta02-cmp06.module",
    "group": "ee.schimke.wearcmp",
    "module": "port-runtime",
    "version": "1.7.0-beta02-cmp06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-jvm-1.7.0-beta02-cmp06.jar",
          "url": "port-runtime-jvm-1.7.0-beta02-cmp06.jar",
          "size": 48088,
          "sha512": "6ea37d64a7c5696b27e2ee85c2ff5d8f594793f5c1a7735f9bf45693d4c39e6fb92fa455eed341e99c54c1d6df141bcff881a1273544d25222a39913171bfa3c",
          "sha256": "2653325b7532df246eb53f97c382f9fa01ae94d9c1b19befa4b4415d73868274",
          "sha1": "64a092c109b3349962b7b6d1be11f8ab0d01779d",
          "md5": "169cc293e1b82c3cf6da0a44a783d9d6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-jvm-1.7.0-beta02-cmp06.jar",
          "url": "port-runtime-jvm-1.7.0-beta02-cmp06.jar",
          "size": 48088,
          "sha512": "6ea37d64a7c5696b27e2ee85c2ff5d8f594793f5c1a7735f9bf45693d4c39e6fb92fa455eed341e99c54c1d6df141bcff881a1273544d25222a39913171bfa3c",
          "sha256": "2653325b7532df246eb53f97c382f9fa01ae94d9c1b19befa4b4415d73868274",
          "sha1": "64a092c109b3349962b7b6d1be11f8ab0d01779d",
          "md5": "169cc293e1b82c3cf6da0a44a783d9d6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "port-runtime-jvm-1.7.0-beta02-cmp06-sources.jar",
          "url": "port-runtime-jvm-1.7.0-beta02-cmp06-sources.jar",
          "size": 33790,
          "sha512": "263cf05a6403656ecab81534bd7e2ae9d98c9a7c84d1ee47858ea7525d248b8b21277505478a97428286db2a6cac483654db3f209f379518095c4c3512ea4a6f",
          "sha256": "d7ecde839bb022923e7ce176ada91d812c8ebad90c4f164cb3075c35339d1786",
          "sha1": "305e5c8ef9f80e6ebc0c95a0a191b1574c27e53b",
          "md5": "3bb62a82c95ed6ba558a6714ee7b20b6"
        }
      ]
    }
  ]
}
