{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wear-compose-material3/1.7.0-beta02-cmp06/wear-compose-material3-1.7.0-beta02-cmp06.module",
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-material3",
    "version": "1.7.0-beta02-cmp06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp06.klib",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp06.klib",
          "size": 2006994,
          "sha512": "7ace0c0b85caa7a61d1cdcee911b886cab829dbd3def63ab192a9dcb62dee30f24abbe4c3608394db2137fa2189d964558e604e9429c987f109c15ac8daf0130",
          "sha256": "508ef07458de7fba888c0d9bd4043625b277b3fd43220e9c1e996819777a273e",
          "sha1": "d0a6cf1f7466b9c9fe0341672ba918ce8bb88971",
          "md5": "1800c13539b55676bb45417270eccd6a"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp06.klib",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp06.klib",
          "size": 2006994,
          "sha512": "7ace0c0b85caa7a61d1cdcee911b886cab829dbd3def63ab192a9dcb62dee30f24abbe4c3608394db2137fa2189d964558e604e9429c987f109c15ac8daf0130",
          "sha256": "508ef07458de7fba888c0d9bd4043625b277b3fd43220e9c1e996819777a273e",
          "sha1": "d0a6cf1f7466b9c9fe0341672ba918ce8bb88971",
          "md5": "1800c13539b55676bb45417270eccd6a"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp06-sources.jar",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp06-sources.jar",
          "size": 470950,
          "sha512": "1c687307848f2b9bb9e87db3b7653b1e6d9873e2310c530995df1ea629deb763f992f7e838f09ed6f5285be36d4eff70fb26063f7f5624cf3574cc45bfeb5ee7",
          "sha256": "bf31f5e9a21eb6eb0544b5e3c37499b4efb386dd43374d5a765167119806f0b0",
          "sha1": "1abb70905749a80660c38f5b1db0ce28279bf090",
          "md5": "4918df499ca10f1eba0b03ec6f3f19b1"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-1.7.0-beta02-cmp06.kotlin_resources.zip",
          "url": "wear-compose-material3-wasm-js-1.7.0-beta02-cmp06-kotlin_resources.kotlin_resources.zip",
          "size": 4531,
          "sha512": "805aac3c66fd38dc276403ec2875326cbcf2616e32e2070f97ca451538a639b6bc17ee83d3eaf909c309435525b69d7e3e2ed9069e970ed2e1c402f58518a018",
          "sha256": "10e305bf63fc2c57b4b42a5a763b13a72eac4c331e1b22957072dcf9e7d7de29",
          "sha1": "2c2d6c8130a4e9c3cd1ae99ce5eac43b22908092",
          "md5": "a52d8f4aa36465cc2ff461f79799e9c7"
        }
      ]
    }
  ]
}
