#!/usr/bin/env bash
# Self-test for the agent-attribution gate.
#
# A gate nobody tests is a gate nobody can safely change — and the failure mode
# that matters here is silent: a detector that stops matching still exits 0 and
# still prints "no agent attribution found". So this exercises both directions,
# what must be REJECTED and what must be LEFT ALONE, against the real scripts.
#
# Runs the detector directly, and drives .githooks/commit-msg and
# .githooks/pre-push end to end in a scratch repo. Needs only git and bash.
#
#   scripts/test-agent-attribution.sh

set -uo pipefail

repo_root="$(git -C "$(dirname "$0")/.." rev-parse --show-toplevel)"
SCAN="$repo_root/.github/scripts/agent-attribution-scan.sh"
HOOK_COMMIT_MSG="$repo_root/.githooks/commit-msg"
HOOK_PRE_PUSH="$repo_root/.githooks/pre-push"

for f in "$SCAN" "$HOOK_COMMIT_MSG" "$HOOK_PRE_PUSH"; do
  if [ ! -x "$f" ]; then
    printf 'missing or non-executable: %s\n' "$f" >&2
    exit 2
  fi
done

# The commit-msg hook enforces Conventional Commits in most of these repos but
# not all of them; only assert it where the hook actually implements it. Detect
# it by the rule itself, not by the words "Conventional Commits" — a hook that
# merely explains why it does NOT enforce them would otherwise look like one
# that does, and the suite would assert behaviour the hook never promised.
enforces_conventional=0
grep -q '^conv_re=' "$HOOK_COMMIT_MSG" && enforces_conventional=1

pass=0; fail=0
check() { # check <label> <expected> <actual>
  if [ "$2" = "$3" ]; then
    pass=$((pass + 1)); printf 'ok   %-58s (exit %s)\n' "$1" "$3"
  else
    fail=$((fail + 1)); printf 'FAIL %-58s (want %s, got %s)\n' "$1" "$2" "$3"
  fi
}

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "== argument handling (must fail closed, never silently pass) =="
"$SCAN" >/dev/null 2>&1;                       check "no arguments -> exit 2" 2 $?
"$SCAN" --bogus x >/dev/null 2>&1;             check "unknown flag -> exit 2" 2 $?
"$SCAN" --range nope123..alsonope >/dev/null 2>&1
                                               check "unresolvable revision -> exit 2" 2 $?

echo
echo "== author / committer identity =="
"$SCAN" --ident author "Claude <noreply@anthropic.com> 1700000000 +0000" >/dev/null 2>&1
                                               check "'Claude <noreply@anthropic.com>' rejected" 1 $?
"$SCAN" --ident author "Yuri Schimke <noreply@anthropic.com> 1700000000 +0000" >/dev/null 2>&1
                                               check "human name + anthropic.com email rejected" 1 $?
"$SCAN" --ident author "Codex <bot@openai.com> 1700000000 +0000" >/dev/null 2>&1
                                               check "'Codex <bot@openai.com>' rejected" 1 $?
"$SCAN" --ident committer "Claude <someone@example.com> 1700000000 +0000" >/dev/null 2>&1
                                               check "committer named literally 'Claude' rejected" 1 $?
"$SCAN" --ident author "Yuri Schimke <yuri@schimke.ee> 1700000000 +0000" >/dev/null 2>&1
                                               check "ordinary human identity accepted" 0 $?
"$SCAN" --ident author "Claude Martin <c.martin@example.com> 1700000000 +0000" >/dev/null 2>&1
                                               check "human named 'Claude Martin' accepted" 0 $?
"$SCAN" --ident author "claude[bot] <1+claude[bot]@users.noreply.github.com> 1700000000 +0000" >/dev/null 2>&1
                                               check "GitHub App bot identity exempt" 0 $?

echo
echo "== Co-authored-by trailers =="
t() { printf '%b' "$1" > "$tmp/msg"; "$SCAN" --text-file "$tmp/msg" >/dev/null 2>&1; }
t 'feat: x\n\nCo-authored-by: Claude <noreply@anthropic.com>\n';        check "agent co-author rejected" 1 $?
t 'feat: x\n\nCo-Authored-By: Claude Opus 4.6 (1M) <noreply@anthropic.com>\n'
                                                                        check "mixed-case trailer with model name rejected" 1 $?
t 'feat: x\n\nCo-authored-by: Codex <codex@openai.com>\n';              check "Codex co-author rejected" 1 $?
t 'feat: x\n\n  Co-authored-by: Claude <noreply@anthropic.com>\n';      check "indented trailer rejected" 1 $?
t 'feat: x\n\nCo-authored-by: claude[bot] <1+claude[bot]@users.noreply.github.com>\n'
                                                                        check "bot co-author trailer rejected" 1 $?
t 'feat: x\n\nCo-authored-by: Yuri Schimke <yuri@schimke.ee>\n';        check "human co-author accepted" 0 $?
t 'feat: x\n\n\xf0\x9f\xa4\x96 Generated with Claude Code\nhttps://claude.ai/code/session_x\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n'
                                                                        check "'Generated with/by' footers + session link accepted" 0 $?
t 'docs: y\n\nWe reject a Co-authored-by: Claude <noreply@anthropic.com> trailer.\n'
                                                                        check "prose mentioning a trailer mid-line accepted" 0 $?

# The trailer vocabulary is deliberately wider than the identity vocabulary and
# must stay that way — these are the providers the pre-existing workflow gates
# covered. Trimming the list silently reopens all four enforcement layers.
t 'feat: x\n\nCo-authored-by: Tabnine <noreply@tabnine.com>\n';         check "Tabnine co-author rejected" 1 $?
t 'feat: x\n\nCo-authored-by: Codeium <bot@codeium.com>\n';             check "Codeium co-author rejected" 1 $?
t 'feat: x\n\nCo-authored-by: Amazon Q <amazonq@example.com>\n';        check "Amazon Q co-author rejected" 1 $?
t 'feat: x\n\nCo-authored-by: CodeWhisperer <cw@example.com>\n';        check "CodeWhisperer co-author rejected" 1 $?
t 'feat: x\n\nCo-authored-by: Cursor <bot@cursor.sh>\n';                check "Cursor co-author rejected" 1 $?
t 'feat: x\n\nCo-authored-by: Cody <bot@sourcegraph.com>\n';            check "Sourcegraph Cody co-author rejected" 1 $?
t 'feat: x\n\nCo-authored-by: copilot-swe-agent[bot] <1+Copilot@users.noreply.github.com>\n'
                                                                        check "copilot-swe-agent[bot] co-author rejected" 1 $?
t 'feat: x\n\nCo-authored-by: gemini-code-assist[bot] <1+gemini-code-assist[bot]@users.noreply.github.com>\n'
                                                                        check "gemini-code-assist[bot] co-author rejected" 1 $?
# ...but non-agent automation is NOT an agent. These land in history routinely
# and must keep passing, or every dependency-bump merge trips the gate.
t 'fix(deps): bump x\n\nCo-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>\n'
                                                                        check "renovate[bot] co-author accepted" 0 $?
t 'chore: release\n\nCo-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>\n'
                                                                        check "github-actions[bot] co-author accepted" 0 $?

echo
echo "== commit-msg and pre-push hooks, end to end =="
up="$tmp/upstream"; w="$tmp/clone"
git init -q --bare "$up"
git init -q -b main "$w"
cd "$w" || exit 2
mkdir -p .github/scripts .githooks
cp "$SCAN" .github/scripts/agent-attribution-scan.sh
cp "$HOOK_COMMIT_MSG" .githooks/commit-msg
cp "$HOOK_PRE_PUSH" .githooks/pre-push
chmod +x .github/scripts/agent-attribution-scan.sh .githooks/commit-msg .githooks/pre-push
git config core.hooksPath .githooks
git config user.name "Test Human"
git config user.email "human@example.com"
git remote add origin "$up"

echo seed > f; git add -A
git commit -q -m "feat: seed" >/dev/null 2>&1;  check "clean commit accepted by commit-msg" 0 $?

echo a >> f; git add -A
git commit -q -m "feat: a" -m "Co-authored-by: Claude <noreply@anthropic.com>" >/dev/null 2>&1
                                                check "commit with agent co-author rejected" 1 $?
git -c user.name=Claude -c user.email=noreply@anthropic.com commit -q -m "feat: a" >/dev/null 2>&1
                                                check "commit made AS an agent rejected" 1 $?
git commit -q -m "feat: a" >/dev/null 2>&1;     check "same commit as a human accepted" 0 $?

# Auto-generated subjects skip the Conventional Commits rule. They must NOT
# skip the attribution scan — a merge or a revert carries an identity and a
# trailer like any other commit.
echo m >> f; git add -A
git commit -q -m "Merge branch 'x'" -m "Co-authored-by: Claude <noreply@anthropic.com>" >/dev/null 2>&1
                                                check "Merge subject does NOT skip the trailer scan" 1 $?
git -c user.name=Claude -c user.email=noreply@anthropic.com \
  commit -q -m "Revert \"feat: a\"" >/dev/null 2>&1
                                                check "Revert subject does NOT skip the identity scan" 1 $?
git commit -q -m "Merge branch 'x'" >/dev/null 2>&1
                                                check "clean merge subject still accepted" 0 $?

if [ "$enforces_conventional" -eq 1 ]; then
  echo b >> f; git add -A
  git commit -q -m "not conventional" >/dev/null 2>&1
                                                check "non-conventional subject rejected" 1 $?
  git commit -q -m "fix(scope): b" >/dev/null 2>&1
                                                check "conventional subject accepted" 0 $?
fi

git push -q origin main >/dev/null 2>&1;        check "pre-push allows a clean branch" 0 $?

# The whole point of pre-push: commits that never ran commit-msg, or that
# changed identity after it ran.
echo c >> f; git add -A
git commit -q --no-verify -m "feat: c" -m "Co-authored-by: Claude <noreply@anthropic.com>"
git push -q origin main >/dev/null 2>&1;        check "pre-push catches a --no-verify'd dirty commit" 1 $?
git reset -q --hard HEAD~1

echo d >> f; git add -A; git commit -q -m "feat: d"
git -c user.name=Codex -c user.email=codex@openai.com \
  commit -q --amend --no-edit --reset-author --no-verify
git push -q origin main >/dev/null 2>&1;        check "pre-push catches an amended-in agent identity" 1 $?
git commit -q --amend --no-edit --reset-author --no-verify
git push -q origin main >/dev/null 2>&1;        check "pre-push allows it once the identity is fixed" 0 $?

# A brand-new branch must be scanned for what IT adds, not for all of history —
# otherwise every new branch trips over pre-existing commits.
git checkout -q -b clean-feature
echo e >> f; git add -A; git commit -q -m "feat: e"
git push -q origin clean-feature >/dev/null 2>&1
                                                check "pre-push allows a clean NEW branch" 0 $?
git checkout -q -b dirty-feature
echo g >> f; git add -A
git commit -q --no-verify -m "feat: g" -m "Co-authored-by: Codex <codex@openai.com>"
git push -q origin dirty-feature >/dev/null 2>&1
                                                check "pre-push rejects a dirty NEW branch" 1 $?

# Regression: a STALE remote-tracking ref must not be usable as an exclusion.
# Put a dirty commit on the remote, cache the ref locally, delete the branch on
# the remote — refs/remotes/origin/parked lingers. Pushing a new branch that
# carries that commit must still be caught, even though the stale ref "covers"
# it. Deriving exclusions from the cached --remotes namespace fails this.
git checkout -q -b parked main
echo s >> f; git add -A
git commit -q --no-verify -m "feat: s" -m "Co-authored-by: Claude <noreply@anthropic.com>"
git push -q --no-verify origin parked >/dev/null 2>&1
git fetch -q origin
git push -q --no-verify origin --delete parked >/dev/null 2>&1
git checkout -q -b revived
git push -q origin revived >/dev/null 2>&1
                                                check "pre-push ignores a STALE remote-tracking ref" 1 $?

echo
printf '%d passed, %d failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
