{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wear-compose-foundation/1.7.0-beta02-cmp06/wear-compose-foundation-1.7.0-beta02-cmp06.module",
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-foundation",
    "version": "1.7.0-beta02-cmp06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-foundation-wasm-js-1.7.0-beta02-cmp06.klib",
          "url": "wear-compose-foundation-wasm-js-1.7.0-beta02-cmp06.klib",
          "size": 803055,
          "sha512": "ae864b5c0d5cdac92f9d455bf3aa7541ae0c1e745c71a61122d46c02d87ca57fc1b7ef537a64a1441a99fc7ab65dc879a657c11d02d935b242ffb4d177b617c5",
          "sha256": "fd3b25656a88a4406d33aad6731cac0e8c186802d5c2d5609a18d5b8170cc429",
          "sha1": "9ef68c3fe5a899610deb65f4b690af9178cd9d1e",
          "md5": "c0dd1311262ba7b8e38f00b56ec29357"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-beta02-cmp06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-foundation-wasm-js-1.7.0-beta02-cmp06.klib",
          "url": "wear-compose-foundation-wasm-js-1.7.0-beta02-cmp06.klib",
          "size": 803055,
          "sha512": "ae864b5c0d5cdac92f9d455bf3aa7541ae0c1e745c71a61122d46c02d87ca57fc1b7ef537a64a1441a99fc7ab65dc879a657c11d02d935b242ffb4d177b617c5",
          "sha256": "fd3b25656a88a4406d33aad6731cac0e8c186802d5c2d5609a18d5b8170cc429",
          "sha1": "9ef68c3fe5a899610deb65f4b690af9178cd9d1e",
          "md5": "c0dd1311262ba7b8e38f00b56ec29357"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "wear-compose-foundation-wasm-js-1.7.0-beta02-cmp06-sources.jar",
          "url": "wear-compose-foundation-wasm-js-1.7.0-beta02-cmp06-sources.jar",
          "size": 226262,
          "sha512": "df64233a376755fa5ffcb0fb93b5da3ec7804f9f850c126837903001afb9fb465dd7fda91640c4ee51cb3a1c8fe86778e96f4c986b968979f009adce34f0b1b8",
          "sha256": "b0925b2cd3f7cdc8717b93dca927a075d1da5376a82f78456a478b05f0770b4b",
          "sha1": "3356141e07cda430c1be8e5aed93e4cc6384615f",
          "md5": "aa6ce0d143f02ea756298443f96d1f9f"
        }
      ]
    }
  ]
}
