{
  "formatVersion": "1.1",
  "component": {
    "url": "../../port-runtime/1.7.0-beta02-cmp04/port-runtime-1.7.0-beta02-cmp04.module",
    "group": "ee.schimke.wearcmp",
    "module": "port-runtime",
    "version": "1.7.0-beta02-cmp04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-wasm-js-1.7.0-beta02-cmp04.klib",
          "url": "port-runtime-wasm-js-1.7.0-beta02-cmp04.klib",
          "size": 61947,
          "sha512": "2b7340a5ddf3eb7b854faed968c0b1fd1090808a6b5c42a00407861a16d2a48128543e3195c3815447b9148cf81d731042c5769dc0afb4614ca8c59bc28e0b4f",
          "sha256": "73c7c1f682b217225c5c098a473666ae0cf98937b5340cb414cdc428e11788e6",
          "sha1": "6f3704e81613356693d4fe6d0d91a256b66df632",
          "md5": "275ea60798c8e7e1607f2119174df69b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-wasm-js-1.7.0-beta02-cmp04.klib",
          "url": "port-runtime-wasm-js-1.7.0-beta02-cmp04.klib",
          "size": 61947,
          "sha512": "2b7340a5ddf3eb7b854faed968c0b1fd1090808a6b5c42a00407861a16d2a48128543e3195c3815447b9148cf81d731042c5769dc0afb4614ca8c59bc28e0b4f",
          "sha256": "73c7c1f682b217225c5c098a473666ae0cf98937b5340cb414cdc428e11788e6",
          "sha1": "6f3704e81613356693d4fe6d0d91a256b66df632",
          "md5": "275ea60798c8e7e1607f2119174df69b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "port-runtime-wasm-js-1.7.0-beta02-cmp04-sources.jar",
          "url": "port-runtime-wasm-js-1.7.0-beta02-cmp04-sources.jar",
          "size": 34997,
          "sha512": "9962f0d6a6b8cccc321d94f13f2252a1b67aa50afa4067e30881a03ce162c2554704c41b42835723497a396ac3acc6d283766bb906dfd74c09beb7bbd219879d",
          "sha256": "c3a0d814a5545729572b4050f87560a7a101beceda8f23b79af64fccefaaf5dc",
          "sha1": "36639de40f404a3e50dce987692f19d3da23d8c9",
          "md5": "8849e4f439ca0068b879eb25dbd00eb5"
        }
      ]
    }
  ]
}
